events {}

http {
    # Load balancer. Sessiya Hazelcast'da bo'lgani uchun "sticky" SHART EMAS.
    upstream app_backend {
        # least_conn = eng kam ulanishga ega instance'ga yuboradi.
        # Round-robin xohlasangiz, quyidagi qatorni o'chirib qo'ying.
        least_conn;

        server app1:8080;
        server app2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_backend;
            # $http_host = "localhost:8080" (port bilan). $host esa portni tashlab
            # yuboradi -> Spring redirect'ni portsiz quradi va brauzer localhost:80'ga
            # urinib xato beradi. Shu bois $http_host ishlatamiz.
            proxy_set_header Host              $http_host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $http_host;
            proxy_set_header X-Forwarded-Port  8080;
        }
    }
}
